name: 部署测试环境

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PULL_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Write version.txt
        run: echo -n ${GITHUB_SHA::7} > version.txt
        working-directory: dist

      - name: Setup OSS
        uses: yizhoumo/setup-ossutil@v2
        with:
          endpoint: https://oss-cn-shanghai.aliyuncs.com
          access-key-id: '${{ secrets.ACCESS_KEY_ID }}'
          access-key-secret: '${{ secrets.ACCESS_KEY_SECRET }}'

      - name: Upload
        run: ossutil sync -u --delete -f -j 1000 ./dist/ oss://laiwei-fe-dev/login/
